// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"radare-core/backend/backend/ent/predicate"
	"radare-core/backend/backend/ent/valuelog"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeValueLog = "ValueLog"
)

// ValueLogMutation represents an operation that mutates the ValueLog nodes in the graph.
type ValueLogMutation struct {
	config
	op            Op
	typ           string
	id            *int
	value1        *int
	addvalue1     *int
	value2        *int
	addvalue2     *int
	timestamp     *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ValueLog, error)
	predicates    []predicate.ValueLog
}

var _ ent.Mutation = (*ValueLogMutation)(nil)

// valuelogOption allows management of the mutation configuration using functional options.
type valuelogOption func(*ValueLogMutation)

// newValueLogMutation creates new mutation for the ValueLog entity.
func newValueLogMutation(c config, op Op, opts ...valuelogOption) *ValueLogMutation {
	m := &ValueLogMutation{
		config:        c,
		op:            op,
		typ:           TypeValueLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withValueLogID sets the ID field of the mutation.
func withValueLogID(id int) valuelogOption {
	return func(m *ValueLogMutation) {
		var (
			err   error
			once  sync.Once
			value *ValueLog
		)
		m.oldValue = func(ctx context.Context) (*ValueLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ValueLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withValueLog sets the old ValueLog of the mutation.
func withValueLog(node *ValueLog) valuelogOption {
	return func(m *ValueLogMutation) {
		m.oldValue = func(context.Context) (*ValueLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ValueLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ValueLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ValueLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ValueLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ValueLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetValue1 sets the "value1" field.
func (m *ValueLogMutation) SetValue1(i int) {
	m.value1 = &i
	m.addvalue1 = nil
}

// Value1 returns the value of the "value1" field in the mutation.
func (m *ValueLogMutation) Value1() (r int, exists bool) {
	v := m.value1
	if v == nil {
		return
	}
	return *v, true
}

// OldValue1 returns the old "value1" field's value of the ValueLog entity.
// If the ValueLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ValueLogMutation) OldValue1(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue1 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue1 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue1: %w", err)
	}
	return oldValue.Value1, nil
}

// AddValue1 adds i to the "value1" field.
func (m *ValueLogMutation) AddValue1(i int) {
	if m.addvalue1 != nil {
		*m.addvalue1 += i
	} else {
		m.addvalue1 = &i
	}
}

// AddedValue1 returns the value that was added to the "value1" field in this mutation.
func (m *ValueLogMutation) AddedValue1() (r int, exists bool) {
	v := m.addvalue1
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue1 resets all changes to the "value1" field.
func (m *ValueLogMutation) ResetValue1() {
	m.value1 = nil
	m.addvalue1 = nil
}

// SetValue2 sets the "value2" field.
func (m *ValueLogMutation) SetValue2(i int) {
	m.value2 = &i
	m.addvalue2 = nil
}

// Value2 returns the value of the "value2" field in the mutation.
func (m *ValueLogMutation) Value2() (r int, exists bool) {
	v := m.value2
	if v == nil {
		return
	}
	return *v, true
}

// OldValue2 returns the old "value2" field's value of the ValueLog entity.
// If the ValueLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ValueLogMutation) OldValue2(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue2 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue2 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue2: %w", err)
	}
	return oldValue.Value2, nil
}

// AddValue2 adds i to the "value2" field.
func (m *ValueLogMutation) AddValue2(i int) {
	if m.addvalue2 != nil {
		*m.addvalue2 += i
	} else {
		m.addvalue2 = &i
	}
}

// AddedValue2 returns the value that was added to the "value2" field in this mutation.
func (m *ValueLogMutation) AddedValue2() (r int, exists bool) {
	v := m.addvalue2
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue2 resets all changes to the "value2" field.
func (m *ValueLogMutation) ResetValue2() {
	m.value2 = nil
	m.addvalue2 = nil
}

// SetTimestamp sets the "timestamp" field.
func (m *ValueLogMutation) SetTimestamp(t time.Time) {
	m.timestamp = &t
}

// Timestamp returns the value of the "timestamp" field in the mutation.
func (m *ValueLogMutation) Timestamp() (r time.Time, exists bool) {
	v := m.timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "timestamp" field's value of the ValueLog entity.
// If the ValueLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ValueLogMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "timestamp" field.
func (m *ValueLogMutation) ResetTimestamp() {
	m.timestamp = nil
}

// Where appends a list predicates to the ValueLogMutation builder.
func (m *ValueLogMutation) Where(ps ...predicate.ValueLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ValueLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ValueLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ValueLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ValueLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ValueLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ValueLog).
func (m *ValueLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ValueLogMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.value1 != nil {
		fields = append(fields, valuelog.FieldValue1)
	}
	if m.value2 != nil {
		fields = append(fields, valuelog.FieldValue2)
	}
	if m.timestamp != nil {
		fields = append(fields, valuelog.FieldTimestamp)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ValueLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case valuelog.FieldValue1:
		return m.Value1()
	case valuelog.FieldValue2:
		return m.Value2()
	case valuelog.FieldTimestamp:
		return m.Timestamp()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ValueLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case valuelog.FieldValue1:
		return m.OldValue1(ctx)
	case valuelog.FieldValue2:
		return m.OldValue2(ctx)
	case valuelog.FieldTimestamp:
		return m.OldTimestamp(ctx)
	}
	return nil, fmt.Errorf("unknown ValueLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ValueLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case valuelog.FieldValue1:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue1(v)
		return nil
	case valuelog.FieldValue2:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue2(v)
		return nil
	case valuelog.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	}
	return fmt.Errorf("unknown ValueLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ValueLogMutation) AddedFields() []string {
	var fields []string
	if m.addvalue1 != nil {
		fields = append(fields, valuelog.FieldValue1)
	}
	if m.addvalue2 != nil {
		fields = append(fields, valuelog.FieldValue2)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ValueLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case valuelog.FieldValue1:
		return m.AddedValue1()
	case valuelog.FieldValue2:
		return m.AddedValue2()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ValueLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case valuelog.FieldValue1:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue1(v)
		return nil
	case valuelog.FieldValue2:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue2(v)
		return nil
	}
	return fmt.Errorf("unknown ValueLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ValueLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ValueLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ValueLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ValueLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ValueLogMutation) ResetField(name string) error {
	switch name {
	case valuelog.FieldValue1:
		m.ResetValue1()
		return nil
	case valuelog.FieldValue2:
		m.ResetValue2()
		return nil
	case valuelog.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	}
	return fmt.Errorf("unknown ValueLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ValueLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ValueLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ValueLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ValueLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ValueLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ValueLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ValueLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ValueLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ValueLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ValueLog edge %s", name)
}
