// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"radare-core/backend/backend/ent/predicate"
	"radare-core/backend/backend/ent/valuelog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ValueLogDelete is the builder for deleting a ValueLog entity.
type ValueLogDelete struct {
	config
	hooks    []Hook
	mutation *ValueLogMutation
}

// Where appends a list predicates to the ValueLogDelete builder.
func (_d *ValueLogDelete) Where(ps ...predicate.ValueLog) *ValueLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ValueLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ValueLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ValueLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(valuelog.Table, sqlgraph.NewFieldSpec(valuelog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ValueLogDeleteOne is the builder for deleting a single ValueLog entity.
type ValueLogDeleteOne struct {
	_d *ValueLogDelete
}

// Where appends a list predicates to the ValueLogDelete builder.
func (_d *ValueLogDeleteOne) Where(ps ...predicate.ValueLog) *ValueLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ValueLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{valuelog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ValueLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
