// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"radare-core/backend/backend/ent/predicate"
	"radare-core/backend/backend/ent/valuelog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ValueLogUpdate is the builder for updating ValueLog entities.
type ValueLogUpdate struct {
	config
	hooks    []Hook
	mutation *ValueLogMutation
}

// Where appends a list predicates to the ValueLogUpdate builder.
func (_u *ValueLogUpdate) Where(ps ...predicate.ValueLog) *ValueLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValue1 sets the "value1" field.
func (_u *ValueLogUpdate) SetValue1(v int) *ValueLogUpdate {
	_u.mutation.ResetValue1()
	_u.mutation.SetValue1(v)
	return _u
}

// SetNillableValue1 sets the "value1" field if the given value is not nil.
func (_u *ValueLogUpdate) SetNillableValue1(v *int) *ValueLogUpdate {
	if v != nil {
		_u.SetValue1(*v)
	}
	return _u
}

// AddValue1 adds value to the "value1" field.
func (_u *ValueLogUpdate) AddValue1(v int) *ValueLogUpdate {
	_u.mutation.AddValue1(v)
	return _u
}

// SetValue2 sets the "value2" field.
func (_u *ValueLogUpdate) SetValue2(v int) *ValueLogUpdate {
	_u.mutation.ResetValue2()
	_u.mutation.SetValue2(v)
	return _u
}

// SetNillableValue2 sets the "value2" field if the given value is not nil.
func (_u *ValueLogUpdate) SetNillableValue2(v *int) *ValueLogUpdate {
	if v != nil {
		_u.SetValue2(*v)
	}
	return _u
}

// AddValue2 adds value to the "value2" field.
func (_u *ValueLogUpdate) AddValue2(v int) *ValueLogUpdate {
	_u.mutation.AddValue2(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *ValueLogUpdate) SetTimestamp(v time.Time) *ValueLogUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *ValueLogUpdate) SetNillableTimestamp(v *time.Time) *ValueLogUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the ValueLogMutation object of the builder.
func (_u *ValueLogUpdate) Mutation() *ValueLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ValueLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValueLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ValueLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValueLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ValueLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(valuelog.Table, valuelog.Columns, sqlgraph.NewFieldSpec(valuelog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value1(); ok {
		_spec.SetField(valuelog.FieldValue1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValue1(); ok {
		_spec.AddField(valuelog.FieldValue1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Value2(); ok {
		_spec.SetField(valuelog.FieldValue2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValue2(); ok {
		_spec.AddField(valuelog.FieldValue2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(valuelog.FieldTimestamp, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ValueLogUpdateOne is the builder for updating a single ValueLog entity.
type ValueLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ValueLogMutation
}

// SetValue1 sets the "value1" field.
func (_u *ValueLogUpdateOne) SetValue1(v int) *ValueLogUpdateOne {
	_u.mutation.ResetValue1()
	_u.mutation.SetValue1(v)
	return _u
}

// SetNillableValue1 sets the "value1" field if the given value is not nil.
func (_u *ValueLogUpdateOne) SetNillableValue1(v *int) *ValueLogUpdateOne {
	if v != nil {
		_u.SetValue1(*v)
	}
	return _u
}

// AddValue1 adds value to the "value1" field.
func (_u *ValueLogUpdateOne) AddValue1(v int) *ValueLogUpdateOne {
	_u.mutation.AddValue1(v)
	return _u
}

// SetValue2 sets the "value2" field.
func (_u *ValueLogUpdateOne) SetValue2(v int) *ValueLogUpdateOne {
	_u.mutation.ResetValue2()
	_u.mutation.SetValue2(v)
	return _u
}

// SetNillableValue2 sets the "value2" field if the given value is not nil.
func (_u *ValueLogUpdateOne) SetNillableValue2(v *int) *ValueLogUpdateOne {
	if v != nil {
		_u.SetValue2(*v)
	}
	return _u
}

// AddValue2 adds value to the "value2" field.
func (_u *ValueLogUpdateOne) AddValue2(v int) *ValueLogUpdateOne {
	_u.mutation.AddValue2(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *ValueLogUpdateOne) SetTimestamp(v time.Time) *ValueLogUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *ValueLogUpdateOne) SetNillableTimestamp(v *time.Time) *ValueLogUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the ValueLogMutation object of the builder.
func (_u *ValueLogUpdateOne) Mutation() *ValueLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the ValueLogUpdate builder.
func (_u *ValueLogUpdateOne) Where(ps ...predicate.ValueLog) *ValueLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ValueLogUpdateOne) Select(field string, fields ...string) *ValueLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ValueLog entity.
func (_u *ValueLogUpdateOne) Save(ctx context.Context) (*ValueLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValueLogUpdateOne) SaveX(ctx context.Context) *ValueLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ValueLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValueLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ValueLogUpdateOne) sqlSave(ctx context.Context) (_node *ValueLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(valuelog.Table, valuelog.Columns, sqlgraph.NewFieldSpec(valuelog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ValueLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, valuelog.FieldID)
		for _, f := range fields {
			if !valuelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != valuelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value1(); ok {
		_spec.SetField(valuelog.FieldValue1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValue1(); ok {
		_spec.AddField(valuelog.FieldValue1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Value2(); ok {
		_spec.SetField(valuelog.FieldValue2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValue2(); ok {
		_spec.AddField(valuelog.FieldValue2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(valuelog.FieldTimestamp, field.TypeTime, value)
	}
	_node = &ValueLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
