// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"radare-core/backend/backend/ent/valuelog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ValueLog is the model entity for the ValueLog schema.
type ValueLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Value1 holds the value of the "value1" field.
	Value1 int `json:"value1,omitempty"`
	// Value2 holds the value of the "value2" field.
	Value2 int `json:"value2,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp    time.Time `json:"timestamp,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ValueLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case valuelog.FieldID, valuelog.FieldValue1, valuelog.FieldValue2:
			values[i] = new(sql.NullInt64)
		case valuelog.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ValueLog fields.
func (_m *ValueLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case valuelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case valuelog.FieldValue1:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value1", values[i])
			} else if value.Valid {
				_m.Value1 = int(value.Int64)
			}
		case valuelog.FieldValue2:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value2", values[i])
			} else if value.Valid {
				_m.Value2 = int(value.Int64)
			}
		case valuelog.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ValueLog.
// This includes values selected through modifiers, order, etc.
func (_m *ValueLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ValueLog.
// Note that you need to call ValueLog.Unwrap() before calling this method if this ValueLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ValueLog) Update() *ValueLogUpdateOne {
	return NewValueLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ValueLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ValueLog) Unwrap() *ValueLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ValueLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ValueLog) String() string {
	var builder strings.Builder
	builder.WriteString("ValueLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("value1=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value1))
	builder.WriteString(", ")
	builder.WriteString("value2=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value2))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ValueLogs is a parsable slice of ValueLog.
type ValueLogs []*ValueLog
