// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ValueLogsColumns holds the columns for the "value_logs" table.
	ValueLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "value1", Type: field.TypeInt},
		{Name: "value2", Type: field.TypeInt},
		{Name: "timestamp", Type: field.TypeTime},
	}
	// ValueLogsTable holds the schema information for the "value_logs" table.
	ValueLogsTable = &schema.Table{
		Name:       "value_logs",
		Columns:    ValueLogsColumns,
		PrimaryKey: []*schema.Column{ValueLogsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ValueLogsTable,
	}
)

func init() {
}
